apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: krgeobuk-dev

resources:
- ../../base

patches:
- path: patch-deployment.yaml

configMapGenerator:
- name: my-pick-admin-client-config
  behavior: merge
  literals:
  - NEXT_PUBLIC_ENVIRONMENT=development
  - NODE_ENV=development
  - NEXT_PUBLIC_ENABLE_DEV_TOOLS=true
  - NEXT_PUBLIC_ENABLE_MOCK_DATA=false

commonLabels:
  environment: development
