apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pick-admin-client
spec:
  replicas: 1  # dev는 1개
  template:
    spec:
      containers:
      - name: my-pick-admin-client
        resources:
          requests:
            cpu: 50m  # dev는 최소 리소스
            memory: 128Mi
          limits:
            cpu: 150m
            memory: 256Mi
