apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: krgeobuk-prod

resources:
- ../../base

patches:
- path: patch-deployment.yaml

configMapGenerator:
- name: portal-server-config
  behavior: merge
  literals:
  - NODE_ENV=production
  - MYSQL_DATABASE=portal_prod
  - CORS_ORIGINS=https://portal.krgeobuk.com,https://admin.krgeobuk.com
  - LOG_LEVEL=info

commonLabels:
  environment: production
