apiVersion: v1
kind: Service
metadata:
  name: auth-server
  labels:
    app: auth-server
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: auth-server
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: tcp
    port: 8010
    targetPort: 8010
    protocol: TCP
  sessionAffinity: None
