apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: krgeobuk-dev

resources:
- ../../base

patches:
- path: patch-deployment.yaml

configMapGenerator:
- name: my-pick-server-config
  behavior: merge
  literals:
  - NODE_ENV=development
  - MYSQL_DATABASE=mypick_dev
  - MYSQL_USER=dev_user
  - CORS_ORIGINS=http://mypick.192.168.0.28.nip.io,http://mypick-admin.192.168.0.28.nip.io
  - LOG_LEVEL=debug

commonLabels:
  environment: development
