apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cluster-issuer-staging.yaml
  - cluster-issuer-prod.yaml

# cert-manager는 공식 매니페스트를 사용하여 설치합니다:
# kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.3/cert-manager.yaml
