apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: krgeobuk-prod

resources:
- ../../base

patches:
- path: patch-deployment.yaml

configMapGenerator:
- name: my-pick-server-config
  behavior: merge
  literals:
  - NODE_ENV=production
  - MYSQL_DATABASE=mypick_prod
  - CORS_ORIGINS=https://mypick.krgeobuk.com,https://mypick-admin.krgeobuk.com
  - LOG_LEVEL=info

commonLabels:
  environment: production
