apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-client
spec:
  replicas: 1  # dev는 1개
  template:
    spec:
      containers:
      - name: auth-client
        resources:
          requests:
            cpu: 50m  # dev는 최소 리소스
            memory: 64Mi
          limits:
            cpu: 150m
            memory: 192Mi
